language: python
python:
  - "2.7"
# HTSeq is not compatible with python3

install: "chmod 700 /home/travis/.python-eggs; mkdir $HOME/.python-eggs; chmod og-w $HOME/.python-eggs; cd src; virtualenv -p python3 .venv; source .venv/bin/activate; python setup.py install; pip install nose -I"
script: "nosetests; ./scripts/flake8.sh"

notifications:
  email: false
